import fs from "node:fs";
import path from "node:path";
import { config } from "../config.js";

const songPath = (id) => path.join(config.songsDir, `${id}.json`);

// Ids are generated by us (randomUUID), but they arrive back from the client in
// URLs, so keep anything that could escape the songs directory out.
export function isValidId(id) {
  return typeof id === "string" && /^[a-zA-Z0-9_-]{6,64}$/.test(id);
}

export function saveSong(song) {
  const record = { ...song, updatedAt: new Date().toISOString() };
  fs.writeFileSync(songPath(record.id), JSON.stringify(record, null, 2), "utf8");
  return record;
}

export function getSong(id) {
  if (!isValidId(id)) return null;
  const file = songPath(id);
  if (!fs.existsSync(file)) return null;
  try {
    return JSON.parse(fs.readFileSync(file, "utf8"));
  } catch {
    return null;
  }
}

/**
 * First stored song matching `predicate`, or null.
 * Used to recognise a song we have already analysed so the download and the
 * whole analysis can be skipped entirely.
 */
export function findSongBy(predicate) {
  if (!fs.existsSync(config.songsDir)) return null;
  for (const name of fs.readdirSync(config.songsDir)) {
    if (!name.endsWith(".json")) continue;
    try {
      const song = JSON.parse(
        fs.readFileSync(path.join(config.songsDir, name), "utf8")
      );
      if (predicate(song)) return song;
    } catch {
      // A corrupt file should not hide the rest of the library.
    }
  }
  return null;
}

/** Look up a previously analysed YouTube video by its id. */
export function findByVideoId(videoId) {
  if (!videoId) return null;
  return findSongBy((song) => song.source?.videoId === videoId);
}

/** Look up a previously analysed upload/recording by its content hash. */
export function findByAudioHash(hash) {
  if (!hash) return null;
  return findSongBy((song) => song.audioHash === hash);
}

export function listSongs() {
  if (!fs.existsSync(config.songsDir)) return [];
  return fs
    .readdirSync(config.songsDir)
    .filter((name) => name.endsWith(".json"))
    .map((name) => {
      try {
        const song = JSON.parse(
          fs.readFileSync(path.join(config.songsDir, name), "utf8")
        );
        // The summary drops blocks/chords so the library list stays small.
        return {
          id: song.id,
          title: song.title,
          artist: song.artist,
          source: song.source,
          key: song.key,
          bpm: song.bpm,
          duration: song.duration,
          thumbnail: song.thumbnail,
          hasLyrics: song.hasLyrics,
          createdAt: song.createdAt,
          updatedAt: song.updatedAt,
        };
      } catch {
        return null;
      }
    })
    .filter(Boolean)
    .sort((a, b) => String(b.createdAt).localeCompare(String(a.createdAt)));
}

export function deleteSong(id) {
  const song = getSong(id);
  if (!song) return false;

  fs.rmSync(songPath(id), { force: true });
  if (song.audioFile) {
    const audio = path.join(config.audioDir, path.basename(song.audioFile));
    fs.rmSync(audio, { force: true });
  }
  return true;
}
